### ISSUE TITLE
Fix package vulnerability 

### ISSUE THREAD

**Issue by Kunamatata** [Kunamatata/Starcraft2-Extension-Server#2]
Move Lodash dependency from `"lodash": "4.17.4",` to `"lodash": "4.17.5",`

**Comment by rameshvishnoi90904** [comment]
is this fixed? @Kunamatata

**Comment by Kunamatata** [comment]
Hey @rameshvishnoi90904 ! This is fixed, I was about to close it. I'll open a new one if your interested :)

**Comment by rameshvishnoi90904** [comment]
@Kunamatata Yes Please

**Comment by Kunamatata** [comment]
@rameshvishnoi90904  please see https://github.com/Kunamatata/Starcraft2ChromeExtension/issues/15
It's the client side of this project 😄
